// Legacy entry point kept for compatibility.
// Core crawlable pages, canonical URLs, metadata and sitemap are now generated by scripts/build-core-pages.mjs.

await import('./scripts/build-core-pages.mjs');
